services:
  jupyter:
    image: DS-Lab/jupyter:1.0
    container_name: 'DS-Lab-jupyter'
    environment:
      - TZ=Asia/Tokyo
    build:
      context: ./jupyter
      args:
        GIT_USER_NAME: ${GIT_USER_NAME:-Your Name}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL:-you@example.com}
    working_dir: '/home/jovyan/work'
    volumes:
      - ${MOUNT_PATH}:/home/jovyan/work
    stdin_open: true
    tty: true
    ports:
      - '8888:8888'
    shm_size: '9gb'